project: visual-flow
imagePullSecret: vf-image-pull

backend:
  createRoles: true
  serviceAccount: 
    name: vf-app-backend
    addSA: true
  deployment:
    replicas: 1
    image:
      repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/iba-group/visual-flow
      tag: 0.9.2-backend
      pullPolicy: Always
    # variables:
    secretVariables:
      KEYSTORE_PASS: "b4hAz8QYVJxDUpv"
      SLACK_API_TOKEN: ""
    sslSecret: vf-app-backend-ssl
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 300m
        memory: 2Gi
  configFile:
    oauth:
      userInfo: "https://api.github.com/user" # "https://gitlab.okd.gomel.iba.by/api/v4/user"
      fieldsMap:
        id: id
        username: login # username
        name: name
        email: email
    superusers: []
    namespace:
      label: vf-app
      prefix: "vf-"
      annotations: {}
    argoServerUrl: "http://vf-app-server:2746"
    sparkJob:
      repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/iba-group/visual-flow
      tag: 0.9.2-spark-job
      jobSA: spark
      jobRB: spark-edit
      addSA: true
      # kubernetesAPI: "k8s://https://kubernetes.default.svc.cluster.local"
    slackJob:
      repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/iba-group/visual-flow
      tag: 0.9.2-slack-notification
      appAPItoken: "${SLACK_API_TOKEN}"
  service:
    type: NodePort # ClusterIP
    port: 8080
    # nodePort:
    annotations:
      # service.beta.openshift.io/serving-cert-secret-name: vf-app-backend-ssl
  subPath: "/vf/be"
  external:
    enabled: false
    type: ingress
    host: localhost
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/group.name: visual-flow
    ssl: {}

frontend:
  deployment:
    replicas: 1
    image:
      repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/iba-group/visual-flow
      tag: 0.9.2-frontend
      pullPolicy: Always
    variables:
      STRATEGY: GITHUB
      API_SERVER: "https://vf-app-backend:8080/vf/be/"
      STRATEGY_CALLBACK_URL: ""
      GITHUB_STRATEGY_BASE_URL: "https://github.com"
    secretVariables:
      GITHUB_APP_ID: ""
      GITHUB_APP_SECRET: ""
      SESSION_SECRET: "a597d68350b02f2d"
    sslSecret: vf-app-frontend-ssl
    resources: {}
  service:
    type: LoadBalancer # NodePort # ClusterIP
    port: 443
    # nodePort:
    annotations:
      # # service.beta.openshift.io/serving-cert-secret-name: vf-app-dev-frontend-ssl
      # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      # # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
      # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      # service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
  subPath: "/vf/ui/"
  external:
    enabled: false
    type: ingress
    host: localhost
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      # alb.ingress.kubernetes.io/group.name: visual-flow
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
      alb.ingress.kubernetes.io/certificate-arn: ""
    ssl: {}
      # cert: |-
      # key: |-
