# release name: vf-app
vf-app:
  install: true
  backend:
    deployment:
      secretVariables:
        SLACK_API_TOKEN: ""
    configFile:
      superusers:
        - 
  frontend:
    deployment:
      secretVariables:
        GITHUB_APP_ID: 
        GITHUB_APP_SECRET: 
vf-secrets:
  install: true
argo:
  install: true
kube-metrics:
  install: true
ingress-nginx:
  install: true
